apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-eligibility-deployment
  labels:
    app: license-eligibility
spec:
  replicas: 3
  selector:
    matchLabels:
      app: license-eligibility
  template:
    metadata:
      labels:
        app: license-eligibility
    spec:
      containers:
      - name: license-eligibility-container
        image: license-eligibility-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: license-eligibility-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: license-eligibility
